apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: local-cluster
  namespace: stackrox
spec:
  clusterName: local-cluster
  admissionControl:
    listenOnCreates: false
    listenOnEvents: true
    listenOnUpdates: false
  perNode:
    collector:
      collection: KernelModule
      imageFlavor: Regular
    taintToleration: TolerateTaints
  sensor:
    resources:
      requests:
        cpu: "200m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "2Gi"
